name = "myatkyawthu"
main = "dist/index.js"
compatibility_date = "2026-03-21"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }
