import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Seed for personal projects (5 projects)
  const Projects = [
    {
      project_id: 'popo-portfolio',
      project_title: 'Aesthetic Portfolio',
      project_subtitle: 'I developed a professional portfolio website for Po Po Thae Khine, a recent accounting graduate, to showcase her qualifications and expertise. The site features sections on her education, certifications (including HSK 2 and NLA FAA Levels 1 & 2), skills in critical thinking and wealth management, and practical experience as a Financial Assistant. It also provides contact information and options to download her CV, effectively presenting her credentials to potential employers.',
      project_cover_img: '/uploads/random-cover1.png',
      project_tech_stacks: [
            "TypeScript",
            "ShadcnUi",
            "Next.js",
            "React",
            "Framer-Motion",
            "GSAP"
        ],
      project_link: 'https://popothaekhine.vercel.app/',
      github_link: 'https://github.com/PrimeBeyonder/Popo',
      project_status: 'Completed',
      personal: true,
      createdAt: new Date('2025-01-15T11:10:00.000Z'),
      updatedAt: new Date('2025-03-02T13:55:00.000Z'),
    },
     {
      project_id: 'bookborrow-app',
      project_title: 'BookBorrow App',
      project_subtitle: 'A modern library management system with AI-powered recommendations.',
      project_description: 'BookBorrow is a library management system featuring AI-driven book recommendations, borrower tracking, and administrative analytics.',
      technical_specifications: 'Frontend: Next.js 15, Backend: Bun; Database: PostgreSQL; Caching: Redis; Payments: Stripe; Email: Resend; UI Components: Shadcn UI; Styling: TailwindCSS; Form Validation: Zod; Animations: Framer Motion',
      project_cover_img: '/uploads/bookborrow-cover.png',
      project_tech_stacks: ["TypeScript" ,'Next.js', 'Bun', 'Prisma', 'PostgreSQL', 'Redis', 'Stripe', 'Resend', 'Shadcn UI', 'TailwindCSS', 'Zod', 'Framer Motion'],
      project_link: 'https://github.com/PrimeBeyonder/full_stack_bookBorrow_app',
      github_link: 'https://github.com/PrimeBeyonder/full_stack_bookBorrow_app',
      project_status: 'In Progress',
      personal: true,
      createdAt: new Date('2025-03-06T10:00:00.000Z'),
      updatedAt: new Date('2025-03-06T10:00:00.000Z'),
    },
    {
    project_id: "zentry-clone",
    project_title: "Zentry Clone",
    project_subtitle: "A clone of Zentry.com to practice advanced UI interactions.",
    project_description: "Zentry Clone is a personal project aimed at replicating the features of Zentry.com, focusing on implementing advanced UI interactions such as scroll-based animations, clip-path shaped transitions, 3D hover effects, and video transitions. Built with React.js, GSAP, TailwindCSS, and JavaScript, this project serves as a practice ground for enhancing front-end development skills.",
    technical_specifications: "Frontend: React.js; Styling: TailwindCSS; Animations: GSAP; Scripting: JavaScript",
    project_cover_img: "/uploads/zentry-clone-cover.png",
    project_tech_stacks: ["React.js", "GSAP", "TailwindCSS", "JavaScript"],
    project_link: "https://github.com/PrimeBeyonder/zentry__",
    github_link: "https://github.com/PrimeBeyonder/zentry__",
    project_status: "Completed",
    personal: true,
    createdAt: new Date("2025-03-06T10:00:00.000Z"),
    updatedAt: new Date("2025-03-06T10:00:00.000Z")
    },
    {
      project_id: 'todo-app',
      project_title: 'Todo App',
      project_subtitle: 'A simple todo app to help users manage their tasks.',
      project_cover_img: '/uploads/random-cover3.png',
      project_tech_stacks: ['React', 'Node.js', 'MongoDB'],
      project_link: 'https://todolist.com',
      github_link: 'https://github.com/user/todo-app',
      project_status: 'Completed',
      personal: true,
      createdAt: new Date('2025-02-10T15:10:20.000Z'),
      updatedAt: new Date('2025-03-04T14:30:00.000Z'),
    },
    {
      project_id: 'recipe-app',
      project_title: 'Recipe Finder',
      project_subtitle: 'An app to find and store your favorite recipes.',
      project_cover_img: '/uploads/random-cover4.png',
      project_tech_stacks: ['Vue.js', 'Firebase', 'TailwindCSS'],
      project_link: 'https://recipeapp.com',
      github_link: 'https://github.com/user/recipe-finder',
      project_status: 'Completed',
      personal: true,
      createdAt: new Date('2025-03-01T13:40:10.000Z'),
      updatedAt: new Date('2025-03-06T10:20:15.000Z'),
    },

    {
      project_id: 'business-website',
      project_title: 'Business Website',
      project_subtitle: 'A full-stack business website for small companies.',
      project_cover_img: '/uploads/random-cover5.png',
      project_tech_stacks: ['Next.js', 'MongoDB', 'Bootstrap'],
      project_link: 'https://businesswebsite.com',
      github_link: 'https://github.com/user/business-website',
      project_status: 'Completed',
      personal: false,
      createdAt: new Date('2024-08-15T11:45:00.000Z'),
      updatedAt: new Date('2025-03-01T10:50:00.000Z'),
    },
    {
      project_id: 'ecommerce-platform',
      project_title: 'E-commerce Platform',
      project_subtitle: 'An e-commerce platform to manage products and users.',
      project_cover_img: '/uploads/random-cover6.png',
      project_tech_stacks: ['React', 'Node.js', 'PostgreSQL'],
      project_link: 'https://ecommerce.com',
      github_link: 'https://github.com/user/ecommerce-platform',
      project_status: 'In Progress',
      personal: false,
      createdAt: new Date('2024-09-05T10:00:00.000Z'),
      updatedAt: new Date('2025-03-01T11:00:00.000Z'),
    },
    {
      project_id: 'chat-app',
      project_title: 'Chat Application',
      project_subtitle: 'A real-time chat app with group and private messaging.',
      project_cover_img: '/uploads/random-cover7.png',
      project_tech_stacks: ['React', 'Socket.IO', 'Express'],
      project_link: 'https://chatapp.com',
      github_link: 'https://github.com/user/chat-app',
      project_status: 'Completed',
      personal: false,
      createdAt: new Date('2024-07-10T15:35:00.000Z'),
      updatedAt: new Date('2025-03-02T12:20:10.000Z'),
    },
    {
      project_id: 'blog-website',
      project_title: 'Personal Blog',
      project_subtitle: 'A blog website where I write articles on tech and programming.',
      project_cover_img: '/uploads/random-cover8.png',
      project_tech_stacks: ['Next.js', 'GraphQL', 'Apollo'],
      project_link: 'https://myblog.com',
      github_link: 'https://github.com/user/blog-website',
      project_status: 'Completed',
      personal: false,
      createdAt: new Date('2024-11-11T16:00:00.000Z'),
      updatedAt: new Date('2025-03-02T14:00:00.000Z'),
    },
    {
      project_id: 'social-media',
      project_title: 'Social Media App',
      project_subtitle: 'A social media app for connecting with friends and sharing posts.',
      project_cover_img: '/uploads/random-cover9.png',
      project_tech_stacks: ['React', 'Firebase', 'TailwindCSS'],
      project_link: 'https://socialmedia.com',
      github_link: 'https://github.com/user/social-media',
      project_status: 'In Progress',
      personal: false,
      createdAt: new Date('2025-01-15T11:00:00.000Z'),
      updatedAt: new Date('2025-03-03T16:30:20.000Z'),
    },
    {
      project_id: 'news-aggregator',
      project_title: 'News Aggregator',
      project_subtitle: 'An app to aggregate news articles from various sources.',
      project_cover_img: '/uploads/random-cover10.png',
      project_tech_stacks: ['Vue.js', 'Vuex', 'Axios'],
      project_link: 'https://newsaggregator.com',
      github_link: 'https://github.com/user/news-aggregator',
      project_status: 'Completed',
      personal: false,
      createdAt: new Date('2025-02-05T14:10:00.000Z'),
      updatedAt: new Date('2025-03-04T13:00:00.000Z'),
    },
    {
      project_id: 'project-management',
      project_title: 'Project Management Tool',
      project_subtitle: 'A tool for managing project tasks, deadlines, and teams.',
      project_cover_img: '/uploads/random-cover11.png',
      project_tech_stacks: ['Angular', 'NestJS', 'MySQL'],
      project_link: 'https://projectmanagement.com',
      github_link: 'https://github.com/user/project-management',
      project_status: 'In Progress',
      personal: false,
      createdAt: new Date('2025-01-10T10:30:00.000Z'),
      updatedAt: new Date('2025-03-05T12:00:30.000Z'),
    },
    {
      project_id: 'movie-database',
      project_title: 'Movie Database',
      project_subtitle: 'A web app to search for movies and display their details.',
      project_cover_img: '/uploads/random-cover12.png',
      project_tech_stacks: ['React', 'TMDB API', 'CSS'],
      project_link: 'https://moviedb.com',
      github_link: 'https://github.com/user/movie-database',
      project_status: 'Completed',
      personal: false,
      createdAt: new Date('2024-10-20T14:15:00.000Z'),
      updatedAt: new Date('2025-03-06T11:40:00.000Z'),
    },
  ];

  // Insert all personal projects
  await prisma.project.createMany({
    data: Projects,
  });

  console.log('Seeding completed!');
}

main()
  .catch(e => {
    throw e
  })
  .finally(async () => {
    await prisma.$disconnect()
  });
